<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

	

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="0.6"/>
  <xacro:property name="base_height" value="0.03"/>
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.03"/>

  <xacro:property name="iphone_height" value="0.165"/>
  <xacro:property name="iphone_width" value="0.02"/>
  <xacro:property name="iphone_length" value="0.09"/>

    <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <!-- iphone mount -->
  <link name="iphone_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${iphone_length} ${iphone_width}  ${iphone_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="$iphone" type="fixed">
      <parent link="base_link"/>
      <child link="iphone_link"/>
      <origin xyz="0 ${base_length/4} ${iphone_height/2+base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- wheels -->
  <xacro:macro name="wheel" params="prefix x y z">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_rear_left" x="${base_width/2+wheel_width/2}" y="${base_length/2 - wheel_radius}" z="0" />
  <xacro:wheel prefix="drivewhl_rear_right" x="${-1*(base_width/2+wheel_width/2)}" y="${base_length/2 - wheel_radius}" z="0" />
  <xacro:wheel prefix="drivewhl_front_left" x="${base_width/2+wheel_width/2}" y="${-1*(base_length/2 - wheel_radius)}" z="0" />
  <xacro:wheel prefix="drivewhl_front_right" x="${-1*(base_width/2+wheel_width/2)}" y="${-1*(base_length/2 - wheel_radius)}" z="0" />
</robot>